### ISSUE TITLE
Create view components for primary and sub navigation structures

### ISSUE THREAD

**Issue by tonyheadford** [DFE-Digital/register-early-career-teachers#166]
Create view components for primary and secondary navigation structures. We can copy NPQ's pretty closely as they are clean `ViewComponent` implementations of the primary and subnav from x-govuk prototype components

[NPQ components here](https://github.com/DFE-Digital/npq-registration/tree/main/app/components/npq_separation)

## Tasks

* [ ] Add custom navigation settings to each layout created in #241
* [ ] Add a secondary navigation menu so DfE admins can drill into specific areas
* [ ] Add a separate layout for the admin section

**Comment by peteryates** [comment]
Note we probably want to look at the newly released [Service Navigation](https://design-system.service.gov.uk/components/service-navigation/) component instead of the x-govuk primary nav (which will soon be deprecated).

**Comment by claire-hughez** [comment]
@peteryates should we pop this one back in the backlog?
