### ISSUE TITLE
Admin console - school pages

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/register-early-career-teachers#426]
We know we're going to need to be able to list, search for and display schools in the admin area. Until we have final designs let's build a basic version we can easily iterate.

Schools should be a top level nav item (in the service nav):

![image](https://github.com/user-attachments/assets/9c4b4970-87a4-4424-b5d1-e802c5916305)

There should be a search field that allows schools to be found by URN or name:

Here's how it looks in ECF1:

![image](https://github.com/user-attachments/assets/bf680902-4501-419e-8a20-756b949cf32d)

## Tasks

* [ ] add Schools to the service nav in the admin area
* [ ] create the necessary routes for listing/viewing schools - use `urn` for in the route for a particular school (`/schools/123456`)
* [ ] add search capability that works similarly to [the teacher search](https://github.com/DFE-Digital/register-early-career-teachers/pull/377)
* [ ] add a school view that for now shows the school's URN, name and address

**Comment by claire-hughez** [comment]
Lorenzo needs to push a few commits to the PR, and now ready for dev review.

**Comment by ltello** [comment]
This is the [review](https://cpd-ec2-review-698-web.test.teacherservices.cloud/)
