### ISSUE TITLE
Create pages to view teacher data

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/register-early-career-teachers#427]
We know we're going to need to be able to list, search for and display teachers in the admin area. Until we have final designs let's build a basic version we can easily iterate.

Teachers should be a top level nav item. In ECF1 they were called _Participants_ but let's just call them Teachers here.
 
![Screenshot from 2024-10-08 11-51-02](https://github.com/user-attachments/assets/c8dd4146-64e1-4967-9cef-e46e2ee2bf61)

There should be a search field that allows teachers to be found by TRN or name. Here's how it looks in ECF1:

![Screenshot from 2024-10-08 12-05-02-obfuscated](https://github.com/user-attachments/assets/ec654dd4-1621-4b0e-984a-525f9cbe75ee)

## Tasks

* [ ] add Teachers to the service nav in the admin area
* [ ] create the necessary routes for listing/viewing teachers - use `trn` for in the route for a particular school (`/teachers/1234567`)
* [ ] Integrate the page with  [`Teachers::Search`](https://github.com/DFE-Digital/register-early-career-teachers/blob/main/app/services/teachers/search.rb)
* [ ] add a teacher view that for now shows the teacher's TRN and name
* [ ] add pagination with Pagy and [the pagination component](https://govuk-components.netlify.app/components/pagination/)

**Comment by gracecbrennan** [comment]
Tony is looking for a way to do a comparison between what is in ECF 1 and what has been pulled in

**Comment by claire-hughez** [comment]
Carrying on,  but have to prioritise other bits.

**Comment by gracecbrennan** [comment]
This is still in progress - will move to next Sprint.

**Comment by claire-hughez** [comment]
I have not reviewed this yet (and would quite like to), but I wonder if asking Nathan or any NPQ migration folks to check and give feedback at all would be helpful?

**Comment by gracecbrennan** [comment]
@tonyheadford to share Friday stand-up
