### ISSUE TITLE
Get a import working in the migration environment

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/register-early-career-teachers#428]
We want to run a full migration with the current migrators to get  a picture of how clean the data is and to see how long it takes.

As the final migrations will all run in Azure it makes sense to test it there in the migration environment.

## Tasks

* [x] Connect the ECF2 migration env to the ECF1 snapshot database
* [x] Add any necessary database credentials to the migration keyvault
* [ ] Run the actual migration 🚅

**Comment by peteryates** [comment]
First two bits are done @tonyheadford, ready for a test run!

**Comment by peteryates** [comment]
@tonyheadford has done this.

![Image](https://github.com/user-attachments/assets/5c11677e-fe19-419d-b5cf-f31da9de2fed)
