### ISSUE TITLE
Add extensions table

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/register-early-career-teachers#570]
Sometimes [inductions are extended](https://ecf-service-manual.education.gov.uk/policy/induction-for-early-career-teachers/#_extension_of_the_induction_period_after_induction_has_concluded) by appropriate bodies:

> The appropriate body may decide to extend where there is insufficient evidence on which a decision can be based or where it would be unreasonable to expect the ECT to have demonstrated satisfactory performance against the Teachers’ Standards for other reasons. These might include:
> * personal crises;
> * illness;
> * disability;
> * issues around the support during induction; or
> * where there is insufficient evidence within induction documentation for a decision to be made about whether the ECT’s performance against the standards is satisfactory.

We need to store these extensions. A teacher can have more than one extension.

## Tasks

* [ ] create a `InductionExtension` model with the columns:
   * `teacher_id` (fk to `teachers`)
   * `extension_terms` (decimal, 1 decimal place only
   * maybe we need to capture the reason or some more info, confirm
* [ ] add the has_many/belongs_to relationships between `Teacher` and `InductionExtension`
* [ ] add tests, etc

**Comment by gracecbrennan** [comment]
@peteryates for review
