### ISSUE TITLE
Split 'record induction outcome' journey into pass/fail

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/register-early-career-teachers#739]
We currently have a placeholder journey for 'Record your outcome'.

We in the design crit that having a big decision controlled by two radio buttons close together might be problematic.

![image](https://github.com/user-attachments/assets/d3db090f-039a-461f-83ba-75862718e5c3)

So we decided that we'd split this into two journeys. They'll look and act really similarly so let's treat these as a single piece of work.

![image](https://github.com/user-attachments/assets/2c3713a2-f3b7-4578-9561-d90556fc3db2)

The forms will work work in the same way as the release flow except they'll also send an update to the TRS API with the outcome value.

## Tasks

* [ ] update `AppropriateBodies::RecordOutcome` so that instead of having one public `#record_outcome!` method it has `#pass!` and `#fail!`
* [ ] make the pass and fail methods:
   * close the ongoing induction period and record the outcome value on it
   * queue a job which will send the outcome and induction completion date to TRS
   * destroy the pending induction period
* [ ] add feature specs covering the flow and view specs for the back button, page titles etc

**Comment by claire-hughez** [comment]
Does this include a confirmation page? Spoke to Kas and Joe and agreed journey is split and will archive the other ticket.

**Comment by claire-hughez** [comment]
By confirmation message I meant a message like, 'Do you definitely wanna fail this person?' But I realise I was super unclear sorry lol.

I don't think it's needed, it just got mentioned in the heuristic testing. But probably less essential now the journey is split.

**Comment by gracecbrennan** [comment]
@emily-prudence-dfe to take a look
