### ISSUE TITLE
Admin console - NOT FINISHED

### ISSUE THREAD

**Issue by kas-madrigal** [DFE-Digital/register-early-career-teachers#798]
## Human activity 

- [ ] Analyse existing activity of AB support team
- [ ] Analyse existing activity of Grant Funding team in the CPD admin tool 
- [ ] Analyse existing activity of Finance team in the CPD admin tool 
- [ ] Analyse existing activity of ECF 1 team in the CPD admin tool 
- [ ] 

## Feature requirements

- [ ] Create user flow scenarios / create data relationships to edit each data point 
- [ ] Lofi screens for each user flow 

## Validation rules 

https://educationgovuk.sharepoint.com/:w:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/Register%20early%20career%20teachers/TRA%20AB%20Portal/How%20to%20handle%20data%20updates%20between%20TRS%20and%20the%20new%20CPD%20induction%20service.docx?d=wf1e89e5602ee486482a67bc2e9636e8b&csf=1&web=1&e=XdxzfN
