### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/register-early-career-teachers#895]
User research has shown repeatedly that admins in both ECF and NPQ have struggled to piece together what happened chonologically. This meant time had to be spent by devs piecing things together using [the audit log](https://github.com/paper-trail-gem/paper_trail). A disadvantage of using record-level audit data for events is that events are often related to multiple records.

For example, when an AB claims an ECT, we might want to see that event when looking at the participant, the AB, the induction period, etc.

This PR proposes a new, better way of recording that information.

The record at the centre is an Event. Events are linked by foreign keys to all the 'domain' models in the app but the foreign keys default to `null`. As we will be organising all of our business logic in the service layer, we will have objects that perform the creation/update/deletion. The intended use is that we wrap the operation in a transaction and write an event at the same time.

The foreign keys should all be set to `on_delete: :nullify so objects in the application can be deleted at will. The events will no longer be linked to any object so at that point we'd be reliant on the title/description for context. Really deletion should also happen through a service object so we can record a deletion event (that won't be accessible through the originating object but will be through the other related ones).

![Events](https://private-user-images.githubusercontent.com/128088/329360722-bbe9f20c-9648-4d8e-8b04-0348fae274c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MDEwOTgsIm5iZiI6MTczMzQwMDc5OCwicGF0aCI6Ii8xMjgwODgvMzI5MzYwNzIyLWJiZTlmMjBjLTk2NDgtNGQ4ZS04YjA0LTAzNDhmYWUyNzRjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQxMjEzMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzcwZjc1Zjk2NjRkYmE3ZjQ4NzA4MzJkNGU5ZGY4ZTI3ODkzMzVhNDg1ZjliNDY3MzM4OGRhYTBiYzIxZGZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PWSPmcbvY-owpMz0hH1WlcDqlaC387XcFeZlaeM6IR4)

We can use the work done in [this NPQ PR](https://github.com/DFE-Digital/npq-registration/pull/1360) as the basis for this functionality.

## Tasks

* [ ] Add the events model. For now it should be linked to `teachers`, `induction_periods`, `appropriate_bodies` and `induction_extensions`.
* [ ] Ensure we're creating events when doing important things - this should happen in the transaction at the completion of each journey:
   * [ ] claiming an ECT
   * [ ] releasing an ECT
   * [ ] passing an ECT's induction
   * [ ] failing an ECT's induction

## Things to keep in mind

* the language should be neutral as the events might be viewed from different places (i.e., from the teacher's POV vs the AB's POV) - so the description should be something like "John Smith was claimed by Some AB Ltd".
